### PR TITLE
(fix) Scoping bug in inlining

### PR DESCRIPTION
**Pull request by jeromesimeon**
Addresses #389 

Signed-off-by: Jerome Simeon <jeromesimeon@me.com>

### CODE REVIEW

**Comment by jeromesimeon** [comment]
This looks better:
```
define constant x : Integer = 1
define function f(x : String) : String { return x ++ "hi" }
return f("hi");
Response. "hihi"
  :  {emit: Event[], response: String, state: Unit}?
define function g(y : String) : String { if x = 1 then return y ++ "hi" else return y ++ "bye" }
return g("boo");
Response. "boohi"
  :  {emit: Event[], response: String, state: Unit}?
```

**Comment by kach** [comment]
A much easier fix would have been to just add the params to the local context before inlining globals. This creates yet another context, which is only used to fix this bug.

**Comment by jeromesimeon** [comment]
Add them with which value?

**Comment by kach** [comment]
dunit would suffice — it just needs to know that the name is in scope, it doesn't care what it is bound to.

**Pull request merged**
