### PR TITLE
Infer types for match

### PR DESCRIPTION
**Pull request by kach**
This completes type inference for ergoc expressions.

### CODE REVIEW

**Comment by kach** [comment]
(Fixed meet/join bugs.)

**Comment by kach** [comment]
Why is Travis failing? I don't understand this lerna error… something about a JSON syntax error? >_<

screen shot 2018-07-30 at 11 52 06 am

**Comment by jeromesimeon** [comment]
@mttrbrts Any idea why Travis tries and publish to npm? It's not a merged PR yet, just the pre-check on the PR? I never have that error when I do a PR from a clone, but here it's from a branch on the main Ergo repo.

**Comment by kach** [comment]
Whoa, Travis is fixed! Quick, can we merge it before the tests start failing again? @jeromesimeon

**Pull request merged**
