### PR TITLE
ergotop, now at an npm near you

### PR DESCRIPTION
**Pull request by kach**
ergo-cli now installs an `ergotop` that does what you expect

### CODE REVIEW

**Comment by kach** [comment]
pfft >_<

**Comment by jeromesimeon** [comment]
O rebase, rebase, wherefore art thou rebase?

**Comment by kach** [comment]
ugh okay fixed presumably

**Comment by kach** [comment]
@jeromesimeon

**Comment by kach** [comment]
lerna is complaining because it tries to publish it. but the _real_ tests pass

**Comment by jeromesimeon** [comment]
let's wait until the current release settles, but let's plan to have another Ergo release soon.

**Pull request merged**
