### PR TITLE
feature(build) : Migrate from Travis CI to GitHub actions 

### PR DESCRIPTION
**Pull request by harsh1206**
**### Related issue #793** 

**Changes**

- Remove .travis.yml and .travis directories in repo .
- Add .github/workflows directory based on those in ./concerto/.github/workflows
-  Remove scripts in ./scripts replace by those found in ./concerto/scripts
-  update package.json

**Author Checklist**

- [x]  Ensure you provide a DCO sign-off for your commits using the --signoff option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests.
- [ ] Commits messages follow AP format.
- [ ] Extend the documentation, if necessary.
- [ ]  Merging to master from fork:branchname

### CODE REVIEW

**Comment by mttrbrts** [comment]
@harsh1206 can you revert the deletion of the `scripts/` directory, please? Many of those scripts are still needed and are unrelated to Travis.

My apologies, my checklist was wrong for this repo.

**Comment by harsh1206** [comment]
ok i'll do that

**Comment by rkotangoor** [comment]
@harsh1206 can you also remove travis line from the readme?
Search for `Build Status` on Readme and please remove that line.

**Comment by rkotangoor** [comment]
> @harsh1206 can you also remove travis line from the readme?
> Search for `Build Status` on Readme and please remove that line.

or maybe update similar to [cicero](https://raw.githubusercontent.com/accordproject/cicero/master/README.md)?
```
  <a href="https://github.com/accordproject/ergo/actions/workflows/build.yml"><img src="https://github.com/accordproject/ergo/actions/workflows/build.yml/badge.svg" alt="Build Status"></a>

```

**Comment by harsh1206** [comment]
the src for the img is wrong i guess , so should i use the one in cicero instead .
https://github.com/accordproject/cicero/actions/workflows/node.js.yml/badge.svg

**Comment by harsh1206** [comment]
the link for the img is broken , so should i use the one in cicero ?

**Comment by mttrbrts** [comment]
> the link for the img is broken , so should i use the one in cicero ?

My guess is that the image won't work until the first run happens (i.e. after this is merged). I'm happy to leave it as it is.

Can you fix the conflict in package-lock.json, please?

**Comment by mttrbrts** [comment]
@harsh1206 Can you add the scripts files from here, please?
https://github.com/accordproject/concerto/tree/master/scripts

I'm investigating why the build is not being triggered by this PR 🤔

**Comment by harsh1206** [comment]
yes, i'll do that

**Comment by mttrbrts** [comment]
@harsh1206 the latest commit is missing the DCO signoff. Follow the guide here to fix it, https://github.com/accordproject/ergo/pull/796/checks?check_run_id=2201629195

**Review by mttrbrts — APPROVED** [review]
Great work, thanks @harsh1206 !

**Comment by harsh1206** [comment]
thanks :)

**Pull request merged**
