### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by jeromesimeon**
- Bug in output type  for default init method
- Rename `Nothing` to `Nil` so that `nil : Nil`

### CODE REVIEW

**Comment by kach** [comment]
What was wrong with just calling it `Unit` [as you proposed](https://github.com/accordproject/ergo/issues/321#issuecomment-407128607)? Having both `Nil` and `Nothing` types is confusing, not to mention now there's a distinction between `none` and `nil` that is hard to explain. And the word "nil" is a legal term that we shouldn't overload with Ergo-specific meaning.

**Comment by jeromesimeon** [comment]
I like `unit : Unit` or 'nil : Nil` but I definitely do not like `nil : Unit`.

**Comment by kach** [comment]
Right, I meant `unit : Unit` (which is what I thought your comment linked above was proposing).

**Comment by jeromesimeon** [comment]
I actually do not like `nil` since it's really not the way `nil` is used in other languages, but you seemed to have a strong opinion about using `nil`. At least now the value and type is consistent.

**Comment by jeromesimeon** [comment]
Damn, I picked the wrong one :) Maybe you can make the next version with `unit : Unit` ?

**Comment by kach** [comment]
Yeah okay I'm going to send a PR.

**Comment by kach** [comment]
#394

**Pull request merged**
