### PR TITLE
Update DEVELOPERS.md

### PR DESCRIPTION
**Pull request by Shivansh2407**
# Issue #<NUMBER HERE>
<OVERALL SUMMARY OF PULL REQUEST>
update DEVELOPERS.md #659

### Changes
- <INSERT DESCRIPTION OF CHANGES>
  - <SUB NOTES OF DESCRIPTIONS>
- <SUMMARIZE ALL COMMITS IN PULL REQUEST>

### Flags
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>

### Related Issues
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>

### CODE REVIEW

**Comment by Shivansh2407** [comment]
Yes it is because there I updated only a link of main repo

**Comment by mttrbrts** [comment]
Thanks @Shivansh2407, however, unfortunately, this is a duplicate PR, @Parikshit-Hooda claimed this one first.  I'll leave this PR for a few days to give @Parikshit-Hooda chance to finish his work in the other PR.

Please see the comment at https://github.com/accordproject/ergo/pull/661#issuecomment-538682969

**Comment by Shivansh2407** [comment]
@irmerk please merge the PR if if you feel the issue is solved

**Comment by irmerk** [comment]
> @irmerk please merge the PR if if you feel the issue is solved

@Shivansh2407 you'll want to refer to @mttrbrts's comment here:

> Thanks @Shivansh2407, however, unfortunately, this is a duplicate PR, @Parikshit-Hooda claimed this one first. I'll leave this PR for a few days to give @Parikshit-Hooda chance to finish his work in the other PR.
> 
> Please see the comment at [#661 (comment)](https://github.com/accordproject/ergo/pull/661#issuecomment-538682969)

**Comment by jeromesimeon** [comment]
Fixed in #672. Closing this PR.

**Pull request closed without merging**
