### PR TITLE
feat(readme): add all contributors section

### PR DESCRIPTION
**Pull request by daniloff200**
related to https://github.com/accordproject/techdocs/issues/83 & https://github.com/accordproject/techdocs/issues/100

@mttrbrts can you please review that PR?

### CODE REVIEW

**Comment by irmerk** [comment]
I believe the error is because there is a script to make sure all files have a license in it. Similar to that here: https://github.com/accordproject/ergo/blob/master/scripts/manualrelease.sh#L1-L13

@jeromesimeon is familiar with the license check, but I believe you just need to add it to the files:
```
✗ License not found in  /home/travis/build/accordproject/ergo/.all-contributorsrc
✗ License not found in  /home/travis/build/accordproject/ergo/scripts/seed_contributors.sh
```

**Comment by daniloff200** [comment]
@irmerk  yeah, you're right, but, for **all-contributorsrc** it does not work, I added the license there, but, no success. Gonna investigate how can I fix it

**Comment by daniloff200** [comment]
@irmerk  fixed ! :beer:

**Comment by jeromesimeon** [comment]
@irmerk @daniloff200 Couple of questions: why isn't the GitHub `contributors` tab not good enough for this? and how are we going to maintain this?

**Comment by daniloff200** [comment]
we can do that with all-contributors bot (it's already enabled in techdocs repo), and as soon, as somebody become a new contributor, you can add him to this section by one command even in PR's comments:

Check discussions here : accordproject/techdocs#83 & accordproject/techdocs#100

**Comment by jeromesimeon** [comment]
> we can do that with all-contributors bot (it's already enabled in techdocs repo), and as soon, as somebody become a new contributor, you can add him to this section by one command even in PR's comments:
> 
> Check discussions here : [accordproject/techdocs#83](https://github.com/accordproject/techdocs/issues/83) & [accordproject/techdocs#100](https://github.com/accordproject/techdocs/issues/100)



> we can do that with all-contributors bot (it's already enabled in techdocs repo), and as soon, as somebody become a new contributor, you can add him to this section by one command even in PR's comments:
> 
> Check discussions here : [accordproject/techdocs#83](https://github.com/accordproject/techdocs/issues/83) & [accordproject/techdocs#100](https://github.com/accordproject/techdocs/issues/100) @jeromesimeon

Thanks for the pointer @daniloff200 I had missed that thread! I added some comments in 
https://github.com/accordproject/techdocs/issues/100

As a maintainer for at least some of the code, I cannot say I'm a big fan of the idea of having that list in the source code itself.

**Comment by irmerk** [comment]
We'll keep this just to `techdocs`, closing this.

**Pull request closed without merging**
